### ISSUE TITLE
[BUG] Fixes to do

### ISSUE THREAD

**Issue by Ai2473** [Ai2473/3arthh4ck#3]
**Very good bugs to fix**
- [ ] Fix Konas compatibility Legacy#330

> 3arthh4ck: src/main/java/me/earth/earthhack/impl/core/mixins/MixinMinecraft.java:490-502
> konas: src/main/java/me/darki/konas/mixin/mixins/MixinMinecraft.java:78-83

- [ ] Fix text rendering issues in some screen areas sometimes (unknown why)
- [ ] Fix announcer crash Legacy#331
- [ ] Fix CA damage indicator not showing some times, also maybe related to Legacy#205
- [ ] Fix the notification timer for the progressbar
- [x] Fix RunClient if possible (also update gradlew?)
- [ ] Make a better ReadMe
- [ ] Fix TargetHud initial position and extended mode armor position
- [ ] Fix SpeedMine BreakCrystal Legacy#327
- [ ] Fix laggy grow render for SpeedMine Legacy#318
- [ ] Fix CA extrapolation crash at least
- [ ] Fix little logoutspots, bots and DuelClear
